import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Gun from 'gun';
import { useRouter } from 'next/router';
import React, { useContext, useState } from 'react';
import Slider from 'rc-slider';
import 'rc-slider/assets/index.css';
import { v4 } from 'uuid';
import { useGunState } from '@altrx/gundb-react-hooks';
import { countBy, isEqual, omit } from 'lodash';
import { loadGetInitialProps } from 'next/dist/shared/lib/utils';
import { useHistory, useLocation } from 'react-router-dom';
import useLocalStorage from '../components/useLocalStorage';
import Scoring from '../components/Scoring';
import MeetingSelector from '../components/MeetingSelector';
import test, { aspot, predicateIs } from '../components/aspot';
import { AsoptWrapper, AspotContext } from '../components/aspot/context';
import useNode from '../components/aspot/useNode';
import { CountOps, Term } from '../components/aspot/type';
import { and, countIs, with, is } from '../components/aspot/find';

const AspotTest = () => {
  const db = useContext(AspotContext);
  db.find(is('predicate')('boss'))
    .groupBy('subject')
    .having(countIs(">", 3))
    .degroup()
    .next(and(with('subject')('subject'), is('predicate')('friend')))
  const v = useNode(db.node('test').s('name'));
  const friends = useNode(db.node('test').s('friend').all()) as [];
  const change = () => { 
    db.node('test').s('name').is(v4()) 
    db.node('test').s('friend').s().s('name').is(v4());
  }
  console.log(friends);
  return (
    <>
    <div>{v}</div><a onClick={change}>Change me</a>
    {friends.map(() => <Friend />)}
    </>
  )
}
const Home: nextpage = () => {
  const router = useRouter();
  const { id } = router.query;
  // test();
  const db = aspot({sentences:[], date:Date.now()});
  db.node('test').s('friend').s().s('name').is(v4());
  const MeetingBody = id ? Scoring : MeetingSelector
    return (
    <div className="container max-w-2xl mx-auto">
      <Head>
        <title>Rate Your Meeting!</title>
        <meta name="description" content="generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <AsoptWrapper db={db} >
          <AspotTest />
          <AspotTest />
        </AsoptWrapper>
        <h1 className={styles.title}>
          Rate your Meeting
        </h1>
          <MeetingBody id={id}/>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="vercel logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
