import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router';
import React, {  } from 'react';
import 'rc-slider/assets/index.css';
import Scoring from '../components/Scoring';
import MeetingSelector from '../components/MeetingSelector';
import { NextPage } from 'next';

const Home: NextPage = () => {

  const router = useRouter();
  const id = Array.isArray(router.query.id) ? router.query.id[0] : router.query.id;
  console.log(router.query);
  // test();
  // const db = localDb(id || 'defaultMeetng');
  //const db = webSocketDB('ws://localhost:8080');
  // const db = aspot(emptyDatabase());
  const MeetingBody = id ? Scoring : MeetingSelector
    return (
    <div className="container max-w-2xl mx-auto">
      <Head>
        <title>Rate Your Meeting!</title>
        <meta name="description" content="generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <h1 className={styles.title}>
          Rate your Meeting
        </h1>
          <MeetingBody id={id || ''}/>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
        created by e2thex
        </a>
      </footer>
    </div>
  )
}

export default Home
